version: "2.2"

services:
  cube:
    image: cubejs/cube:latest
    ports:
      - 4000:4000
      - 15432:15432
    environment:
      - CUBEJS_DEV_MODE=true
    volumes:
      - .:/cube/conf

  minio:
    image: minio/minio
    container_name: minio1
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=youraccesskey
      - MINIO_ROOT_PASSWORD=yoursecretkey
    command: server /data --console-address ":9001"

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - 5000:3000