{{ config(materialized='table') }}

SELECT "norrænt vörunúmer" AS product_number,
       "lyfjaheitisnúmer" AS product_code,
       "heiti lyfs" AS name,
       "form lyfs" AS form,
       styrkur AS strength,
       styrkeining AS strength_unit,
       magn AS quantity,
       magneining AS quantity_unit,
       "fj. pakkninga" AS number_of_packages,
       pakkning AS packaging,
       athugasemdir AS comments,
       "atc-flokkur" AS atc_category,
       "skráningardagsetning" AS registration_date,
       "afskráningardagsetning" AS deregistration_date,
       "afgreiðslumáti" AS dispensing_method,
       "skömmtunarmöguleikar" AS dosage_options,
       "Öryggiskröfur LST" AS is_safety_requirements_lst,
       eftirritunarskylt AS is_prescription_required,
       "sérfræðingur ávísar" AS specialist_referral,
       "greiðsluhlutur sÍ" AS insurance_share,
       "sjúkrahúslyf" AS is_hospital_drug,
       "markaðsleyfishafi kóði" AS market_agent_code,
       "dýralæknir ávísar" AS is_veterinarian_referral,
       "leyfisskyld lyf" AS is_prescription_drug,
       "tannlæknir ávísar" AS is_dentist_referral,
       "skammtur, hámark daga" AS maximum_dosage_days,
       "viðmiðunargjaldmiðill" AS reference_price_currency,
       CAST(regexp_replace("hámarks heildsöluverð", '\.', '') AS INT) AS maximum_wholesale_price,
       CAST(regexp_replace("hámarks smásöluverð", '\.', '') AS INT) AS maximum_retail_price,
       "Álagningarflokkur" AS classification_category,
       "viðmiðunarverðflokkur" AS reference_price_category,
       "viðmiðunarverð" AS reference_price,
       "staða lyfs" AS drug_status,
       "heildarmagn" AS total_quantity,
       "Á undanþágulista" AS is_on_exemption_list,
       "ddd á pakkningu" AS ddd_per_package,
       "umboðsaðili" AS distributor,
       "markaðsleyfishafi" AS market_agent,
       "heiti virka innihaldsefnis" AS active_ingredient_name,
       "lyfjaframleiðenda heildsöluverð" AS wholesale_price_from_manufacturer,
       CAST(regexp_replace("umboðsmanna heildsöluverð", '\.', '') AS INT) AS distributor_wholesale_price,
       "heildsölu heildsöluverð" AS total_wholesale_price,
       CAST(regexp_replace("innkaupsverð apóteka", '\.', '') AS INT) AS pharmacy_purchase_price,
       CAST(regexp_replace("greiðsluþátttökuverð", '\.', '') AS INT) AS co_payment_price,
       "fellt úr lyfjaverðskrá vegna birgðaskorts" AS removed_from_drug_list_due_to_shortage,
       "heildsali" AS is_wholesale,
       "gtin númer" AS gtin_number,
       "h merking" AS is_h_marked,
       "Ákvörðun LGN um greiðsluþátttöku" AS co_payment_code,
       file_name,
       extracted_date,
       "Ávana og fíknilyf" AS addiction_and_substance_abuse_drug,
       "Ávana og fíknilyf magn" AS addiction_and_substance_abuse_drug_quantity,
       "Ávana og fíknilyf eining" AS addiction_and_substance_abuse_drug_unit,
       "hjúkr-/ljósm ávísar" AS psychiatrist_referral,
       "skömmtunarmöguleikar" AS dosage_options,
       "leyfisskyld lyf" AS prescription_drug,
       "staða lyfs" AS drug_status,
       "Ákvörðun LST um greiðsluþátttöku" AS decision_lst_on_co_payment,
       "greitt fyrir afgreiðslu" AS paid_for_dispensing,
       "einingarverð" AS unit_price,
       "skiptiskrá" AS exchange_register
FROM {{ source('meds', 'stage_pricing') }}